# A股量化交易策略参数配置文件

# 通用配置参数 (所有策略共享)
# ===========================

# Redis缓存配置
redis:
  host: "localhost"
  port: 6379
  db: 0
  password: ""
  ttl: 86400  # 缓存过期时间(秒)，默认1天

# 数据获取参数
data:
  tushare_token: "123"  # 可通过环境变量TUSHARE_TOKEN覆盖
  start_date: "2023-05-01"  # 回测开始日期
  end_date: "2023-12-31"    # 回测结束日期
  universe: "A"             # 股票池: A=所有A股
  refresh_indicator: true   # 是否强制刷新数据缓存
  lookback_period: 10       # 指标计算所需的历史数据天数
  
  # 股票筛选条件
  stock_filters:
    exclude_st: true                # 排除ST股票
    min_listing_days: 60            # 最小上市天数（约2个月）

# 资金管理参数
capital:
  initial: 1000000          # 初始资金(元)
  max_positions: 10         # 最大持仓数量
  position_sizing: "equal"  # 仓位分配方式: equal=等权, dynamic=动态

# 回测评估参数
evaluation:
  benchmark: "000300.SH"    # 基准指数: 沪深300
  output_benchmark_details: true  # 输出基准指数详细信息
  output_daily_records: true      # 输出每日交易记录到CSV文件
  
  # 交易费用参数
  transaction_costs:
    commission_rate: 0.00025      # 佣金费率 (万分之2.5)
    stamp_duty_rate: 0.001        # 印花税 (卖出时千分之1)
    min_commission: 5.0           # 最低佣金(元)
  
  # 持仓比例参数
  position_limits:
    max_position_ratio: 0.20      # 单只股票最大持仓比例 (20%)
    min_position_ratio: 0.05      # 单只股票最小持仓比例 (5%)

# 基本面筛选参数
fundamental:
  min_gross_margin: 20.0    # 最低毛利率(%)
  min_roe: 5.0              # 最低ROE(%)
  min_roa: 0.0              # 最低ROA(%)（可选）
  max_pe: 60.0              # 市盈率
  max_pb: 10.0              # 最高市净率（可选）

# 策略配置参数 (每个策略独立)
# ===========================
strategies:
  # 默认策略 - Supertrend多重指标策略
  default:
    # Supertrend参数
    supertrend:
      st1:
        factor: 3
        period: 12
      st2:
        factor: 1
        period: 10
      st3:
        factor: 2
        period: 11
    
    # EMA参数
    ema:
      length: 144               # EMA周期
    
    # Ichimoku云层参数
    ichimoku:
      conversion_periods: 9     # 转折线周期
      base_periods: 26          # 基准线周期
      lagging_span_periods: 52  # 延迟跨度周期
    
    # 周线均线参数
    weekly_ma:
      ma1_period: 13            # 13周均线周期
      ma2_period: 34            # 34周均线周期
    
    # 量能参数
    volume:
      multiplier: 1.5           # 放量倍数
      turnover_threshold: 3.0   # 最低换手率(%)
      ma_period: 20             # 成交量均线周期
    
    # 筹码集中度参数
    chip_concentration:
      threshold: 30             # 筹码集中度阈值(%)
    
    # 止盈止损参数
    exit:
      take_profit: 20           # 止盈百分比(%)
      stop_loss: 10             # 止损百分比(%)
    
    # RSI超买过滤参数
    rsi:
      period: 14                # RSI周期
      overbought: 60            # 超买阈值
  
  # 策略2 - 保守型Supertrend策略
  conservative:
    # Supertrend参数 - 更保守的设置
    supertrend:
      st1:
        factor: 4
        period: 14
      st2:
        factor: 2
        period: 12
      st3:
        factor: 3
        period: 13
    
    # EMA参数 - 更长的周期
    ema:
      length: 200               # EMA周期
    
    # Ichimoku云层参数
    ichimoku:
      conversion_periods: 9     # 转折线周期
      base_periods: 26          # 基准线周期
      lagging_span_periods: 52  # 延迟跨度周期
    
    # 周线均线参数
    weekly_ma:
      ma1_period: 13            # 13周均线周期
      ma2_period: 34            # 34周均线周期
    
    # 量能参数 - 更高的要求
    volume:
      multiplier: 2.0           # 放量倍数
      turnover_threshold: 4.0   # 最低换手率(%)
      ma_period: 20             # 成交量均线周期
    
    # 筹码集中度参数 - 更高的要求
    chip_concentration:
      threshold: 40             # 筹码集中度阈值(%)
    
    # 止盈止损参数 - 更早止损
    exit:
      take_profit: 15           # 止盈百分比(%)
      stop_loss: 8              # 止损百分比(%)
    
    # RSI超买过滤参数 - 更低的超买阈值
    rsi:
      period: 14                # RSI周期
      overbought: 55            # 超买阈值
  
  # 策略3 - 涨停智能策略 (全新实现)
  aggressive:
    # 涨停策略参数
    limit_up:
      lookback_days: 11         # 检查涨停的回溯天数
      exclude_consecutive: 3    # 排除连续涨停天数
    
    # 月线MACD参数
    monthly_macd:
      fast_period: 6            # 快线周期
      slow_period: 13           # 慢线周期
      signal_period: 5          # 信号线周期
    
    # EMA参数
    ema:
      length: 20                # EMA周期
      price_range: 0.05         # 价格在EMA附近的范围 (±5%)
    
    # 量能参数
    volume:
      multiplier: 1.2           # 放量倍数 (相对于10日均量)
      turnover_threshold: 3.0   # 最低换手率(%)
      ma_period: 10             # 成交量均线周期
    
    # 部分止盈参数
    exit:
      take_profit: 60           # 完全止盈百分比(%)
      stop_loss: 10             # 止损百分比(%)
      partial_take_profit1: 30  # 第一次部分止盈点(%)
      partial_take_profit2: 50  # 第二次部分止盈点(%)
      partial_ratio1: 0.33      # 第一次部分止盈比例 (1/3)
      partial_ratio2: 0.5       # 第二次部分止盈比例 (1/2)
    
    # RSI超买过滤参数
    rsi:
      period: 14                # RSI周期
      overbought: 75            # 超买阈值