# A股量化交易策略参数配置文件

# 通用配置参数 (所有策略共享)
# ===========================

# Redis缓存配置
redis:
  host: "localhost"
  port: 6379
  db: 0
  password: ""
  ttl: 86400  # 缓存过期时间(秒)，默认1天

# 数据获取参数
data:
  tushare_token: "123"  # 可通过环境变量TUSHARE_TOKEN覆盖
  start_date: "2024-01-01"  # 回测开始日期
  end_date: "2024-02-28"    # 回测结束日期
  universe: "A"             # 股票池: A=所有A股
  
  # 股票筛选条件
  stock_filters:
    exclude_st: true                # 排除ST股票
    min_listing_days: 60            # 最小上市天数（约2个月）

# 资金管理参数
capital:
  initial: 1000000          # 初始资金(元)
  max_positions: 10         # 最大持仓数量
  position_sizing: "equal"  # 仓位分配方式: equal=等权, dynamic=动态

# 回测评估参数
evaluation:
  benchmark: "000300.SH"    # 基准指数: 沪深300
  output_benchmark_details: true  # 输出基准指数详细信息

# 基本面筛选参数
fundamental:
  min_gross_margin: 20.0    # 最低毛利率(%)
  min_roe: 5.0              # 最低ROE(%)
  min_roa: 0.0              # 最低ROA(%)（可选）
  max_pe: 60.0              # 市盈率
  max_pb: 10.0              # 最高市净率（可选）

# 策略配置参数 (每个策略独立)
# ===========================
strategies:
  # 默认策略 - Supertrend多重指标策略
  default:
    # Supertrend参数
    supertrend:
      st1:
        factor: 3
        period: 12
      st2:
        factor: 1
        period: 10
      st3:
        factor: 2
        period: 11
    
    # EMA参数
    ema:
      length: 144               # EMA周期
    
    # Ichimoku云层参数
    ichimoku:
      conversion_periods: 9     # 转折线周期
      base_periods: 26          # 基准线周期
      lagging_span_periods: 52  # 延迟跨度周期
    
    # 周线均线参数
    weekly_ma:
      ma1_period: 13            # 13周均线周期
      ma2_period: 34            # 34周均线周期
    
    # 量能参数
    volume:
      multiplier: 1.5           # 放量倍数
      turnover_threshold: 3.0   # 最低换手率(%)
      ma_period: 20             # 成交量均线周期
    
    # 筹码集中度参数
    chip_concentration:
      threshold: 30             # 筹码集中度阈值(%)
    
    # 止盈止损参数
    exit:
      take_profit: 20           # 止盈百分比(%)
      stop_loss: 10             # 止损百分比(%)
    
    # RSI超买过滤参数
    rsi:
      period: 14                # RSI周期
      overbought: 60            # 超买阈值
  
  # 策略2 - 保守型Supertrend策略
  conservative:
    # Supertrend参数 - 更保守的设置
    supertrend:
      st1:
        factor: 4
        period: 14
      st2:
        factor: 2
        period: 12
      st3:
        factor: 3
        period: 13
    
    # EMA参数 - 更长的周期
    ema:
      length: 200               # EMA周期
    
    # Ichimoku云层参数
    ichimoku:
      conversion_periods: 9     # 转折线周期
      base_periods: 26          # 基准线周期
      lagging_span_periods: 52  # 延迟跨度周期
    
    # 周线均线参数
    weekly_ma:
      ma1_period: 13            # 13周均线周期
      ma2_period: 34            # 34周均线周期
    
    # 量能参数 - 更高的要求
    volume:
      multiplier: 2.0           # 放量倍数
      turnover_threshold: 4.0   # 最低换手率(%)
      ma_period: 20             # 成交量均线周期
    
    # 筹码集中度参数 - 更高的要求
    chip_concentration:
      threshold: 40             # 筹码集中度阈值(%)
    
    # 止盈止损参数 - 更早止损
    exit:
      take_profit: 15           # 止盈百分比(%)
      stop_loss: 8              # 止损百分比(%)
    
    # RSI超买过滤参数 - 更低的超买阈值
    rsi:
      period: 14                # RSI周期
      overbought: 55            # 超买阈值
  
  # 策略3 - 激进型Supertrend策略
  aggressive:
    # Supertrend参数 - 更激进的设置
    supertrend:
      st1:
        factor: 2
        period: 10
      st2:
        factor: 1
        period: 8
      st3:
        factor: 1.5
        period: 9
    
    # EMA参数 - 更短的周期
    ema:
      length: 100               # EMA周期
    
    # Ichimoku云层参数
    ichimoku:
      conversion_periods: 7     # 转折线周期
      base_periods: 22          # 基准线周期
      lagging_span_periods: 44  # 延迟跨度周期
    
    # 周线均线参数
    weekly_ma:
      ma1_period: 8             # 8周均线周期
      ma2_period: 21            # 21周均线周期
    
    # 量能参数 - 更宽松的要求
    volume:
      multiplier: 1.2           # 放量倍数
      turnover_threshold: 2.0   # 最低换手率(%)
      ma_period: 15             # 成交量均线周期
    
    # 筹码集中度参数 - 更宽松的要求
    chip_concentration:
      threshold: 25             # 筹码集中度阈值(%)
    
    # 止盈止损参数 - 更高的止盈
    exit:
      take_profit: 25           # 止盈百分比(%)
      stop_loss: 12             # 止损百分比(%)
    
    # RSI超买过滤参数 - 更高的超买阈值
    rsi:
      period: 14                # RSI周期
      overbought: 70            # 超买阈值